service:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prod_php_container
    volumes:
      - ./uploads:/var/www/html
    ports:
      - "127.0.0.1:9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always